In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/jobs_raw.csv") 
df.head()

,job_id,job_title,company,location,posted_date,collected_date,years_experience_required,skills,source_website,job_url,work_model,notes
0,SWD001,Azure Developer,HiQ Finland,Helsinki,30/8/2026,30/9/2026,5,Azure;AWS;REST API;Git;SQL;DevOps;CI/CD;Java;P...,LinkedIn,https://www.linkedin.com/jobs/view/4446623744/,Hybrid,NaN
1,SWD002,IT Developer,GreenGold Group,Kuopio,9/9/2026,30/9/2026,2,PHP;Symfony;Git;Docker;Linux;Bash script;Nginx...,LinkedIn,https://www.linkedin.com/jobs/view/4463026176/,Hybrid,NaN
2,SWD003,Software Developer,Twoday,Helsinki,15/9/2026,30/9/2026,3,"C#; .NET;Vue;React;TypeScript;PostgreSQL, Mari...",LinkedIn,https://www.linkedin.com/jobs/view/4465549066/,Hybrid,NaN
3,SWD004,Software Developer,Wolt,Helsinki,15/9/2026,30/9/2026,Unknown,"Python;Go;AI tools;AWS;Kubernetes, Docker;Data...",LinkedIn,https://www.linkedin.com/jobs/view/4466174195/,On-site,NaN
4,SWD005,Software Developer,Elekta,Helsinki,25/9/2026,30/9/2026,3,REST API;C#;TypeScript;Angular;SQL;CI/CD,LinkedIn,https://www.linkedin.com/jobs/view/4471649152/,On-site,NaN

In [1]:
import os
os.getcwd()

'/Users/hoangtran/Documents/finnish-it-job-market-analysis/notebooks'

In [ ]:
df.info()

In [4]:
df["years_experience_required"].unique()

<StringArray>
['5', '2', '3', 'Unknown', 'Unkown', nan, '3-5']
Length: 7, dtype: str

In [6]:
df[df["years_experience_required"].isin(["Unknown","Unkown"])]

,job_id,job_title,company,location,posted_date,collected_date,years_experience_required,skills,source_website,job_url,work_model,notes
3,SWD004,Software Developer,Wolt,Helsinki,15/9/2026,30/9/2026,Unknown,"Python;Go;AI tools;AWS;Kubernetes, Docker;Data...",LinkedIn,https://www.linkedin.com/jobs/view/4466174195/,On-site,NaN
5,SWD006,Application Developer,Napa,Outokumpu,22/9/2026,30/9/2026,Unknown,AMK/University;English;Finnish;TypeScript;Java...,LinkedIn,https://www.linkedin.com/jobs/view/4468573827/,Hybrid,NaN
6,SWD007,Junior Fullstack - developer,Evolver,Helsinki,1/10/2026,1/10/2026,Unknown,Java; Kotlin;TypeScript;,LinkedIn,https://www.linkedin.com/jobs/view/4473786779/,Hybrid,NaN
7,SWD008,Backend Enginner,Star IT,Espoo,1/9/2026,1/10/2026,Unknown,C#;ASP.NET;EF Core;JWT;API;AI tools;xUnit;,LinkedIn,https://www.linkedin.com/jobs/view/4459957082/,On-site,NaN
9,SWD010,Applied AI Engineer,Euro-Biomaging,Turku,19/9/2026,1/10/2026,Unknown,UX/HCI;Python;FastAPI;Django;PostgreSQL;AI/LLM,LinkedIn,https://www.linkedin.com/jobs/view/4466083732/,Hybrid,NaN
10,SWD011,Senior Developer,Moder.app,Helsinki,27/9/2026,1/10/2026,Unknown,Vue/React;AI tools;UX;,LinkedIn,https://www.linkedin.com/jobs/view/4471444873/,Hybrid;Remote,Remote in Finland
11,DTA001,Data Analyst,Innofactor,Espoo,27/9/2026,1/10/2026,Unknown,Power BI; SQL;Microsoft Fabric;AI tools,LinkedIn,https://www.linkedin.com/jobs/view/4467370865/,Hybrid,NaN
13,DTA003,Senior Data Analyst,Greenstep,Turku,20/9/0206,1/10/2026,Unkown,DAX;M;SQL;Microsoft Fabric; Dataflows; Data Fa...,LinkedIn,https://www.linkedin.com/jobs/view/4463456129/,Hybrid,NaN
15,DTE001,Data Engineer,Saka,Oulu,27/9/2026,1/10/2026,Unknown,SQL;Python;CI/CD;GCP;AWS;Azure,LinkedIn,https://www.linkedin.com/jobs/view/4468531086/,Hybrid,NaN
16,DTE002,Data Engineer,Amesan Consulting Oy,Helsinki,27/9/2026,1/10/2026,Unknown,PostgreSQL;Python;SQL;ETL/ELT;AI tools,LinkedIn,https://www.linkedin.com/jobs/view/4468571901/,Hybrid,NaN

In [ ]:
df[df["years_experiences_required"].isna()]